use Husky_Hacks;
INSERT INTO alert_type (type_id, type_name) VALUES (1, 'Feedback Request');
INSERT INTO alert_type (type_id, type_name) VALUES (2, 'New Project Assigned');
INSERT INTO alert_type (type_id, type_name) VALUES (3, 'Report Submission');
INSERT INTO alert_type (type_id, type_name) VALUES (4, 'Permission Update');
INSERT INTO alert_type (type_id, type_name) VALUES (5, 'System Error');
INSERT INTO alert_type (type_id, type_name) VALUES (6, 'Progress Review');
INSERT INTO alert_type (type_id, type_name) VALUES (7, 'Archived Data Notice');
INSERT INTO alert_type (type_id, type_name) VALUES (8, 'New Notification');
INSERT INTO alert_type (type_id, type_name) VALUES (9, 'Alert Threshold Exceeded');
INSERT INTO alert_type (type_id, type_name) VALUES (10, 'User Status Change');