use Husky_Hacks;
insert into data_source (source_name, data_type) values ('Google Analytics', 'user_engagement');
insert into data_source (source_name, data_type) values ('Mixpanel', 'retention');
insert into data_source (source_name, data_type) values ('Amplitude', 'user_engagement');
insert into data_source (source_name, data_type) values ('Firebase', 'retention');
insert into data_source (source_name, data_type) values ('Heap Analytics', 'conversion_rate');
insert into data_source (source_name, data_type) values ('Segment', 'data_collection');
insert into data_source (source_name, data_type) values ('Klaviyo', 'email_metrics');
insert into data_source (source_name, data_type) values ('PostHog', 'user_engagement');
insert into data_source (source_name, data_type) values ('Snowflake', 'data_warehouse');
insert into data_source (source_name, data_type) values ('Looker', 'dashboard');
insert into data_source (source_name, data_type) values ('Tableau', 'dashboard');
insert into data_source (source_name, data_type) values ('Power BI', 'dashboard');
insert into data_source (source_name, data_type) values ('Adobe Analytics', 'user_engagement');
insert into data_source (source_name, data_type) values ('Hotjar', 'session_replay');
insert into data_source (source_name, data_type) values ('Crazy Egg', 'heatmap');
insert into data_source (source_name, data_type) values ('Optimizely', 'A/B_testing');
insert into data_source (source_name, data_type) values ('VWO', 'A/B_testing');
insert into data_source (source_name, data_type) values ('FullStory', 'session_replay');
insert into data_source (source_name, data_type) values ('Google Tag Manager', 'data_collection');
insert into data_source (source_name, data_type) values ('HubSpot', 'email_metrics');
insert into data_source (source_name, data_type) values ('Mailchimp', 'email_metrics');
insert into data_source (source_name, data_type) values ('Marketo', 'email_metrics');
insert into data_source (source_name, data_type) values ('Salesforce', 'CRM');
insert into data_source (source_name, data_type) values ('Zendesk', 'customer_support');
insert into data_source (source_name, data_type) values ('Intercom', 'customer_support');
insert into data_source (source_name, data_type) values ('Drift', 'chat_metrics');
insert into data_source (source_name, data_type) values ('Pendo', 'user_engagement');
insert into data_source (source_name, data_type) values ('Appcues', 'onboarding_metrics');
insert into data_source (source_name, data_type) values ('Outbrain', 'ad_performance');
insert into data_source (source_name, data_type) values ('Taboola', 'ad_performance');
insert into data_source (source_name, data_type) values ('Google Ads', 'ad_performance');
insert into data_source (source_name, data_type) values ('Facebook Ads', 'ad_performance');
insert into data_source (source_name, data_type) values ('LinkedIn Ads', 'ad_performance');
insert into data_source (source_name, data_type) values ('Twitter Ads', 'ad_performance');
insert into data_source (source_name, data_type) values ('TikTok Ads', 'ad_performance');
insert into data_source (source_name, data_type) values ('Instagram Ads', 'ad_performance');
insert into data_source (source_name, data_type) values ('Spotify Ads', 'audio_metrics');
insert into data_source (source_name, data_type) values ('YouTube Analytics', 'video_metrics');
insert into data_source (source_name, data_type) values ('Zoom', 'webinar_engagement');
insert into data_source (source_name, data_type) values ('GoToWebinar', 'webinar_engagement');
insert into data_source (source_name, data_type) values ('Slack', 'internal_metrics');
insert into data_source (source_name, data_type) values ('Trello', 'project_tracking');
insert into data_source (source_name, data_type) values ('Asana', 'project_tracking');
insert into data_source (source_name, data_type) values ('Monday.com', 'project_tracking');
insert into data_source (source_name, data_type) values ('ClickUp', 'project_tracking');
insert into data_source (source_name, data_type) values ('Basecamp', 'project_tracking');
insert into data_source (source_name, data_type) values ('Jira', 'project_tracking');
insert into data_source (source_name, data_type) values ('GitHub', 'version_control');
insert into data_source (source_name, data_type) values ('Bitbucket', 'version_control');
insert into data_source (source_name, data_type) values ('GitLab', 'version_control');
insert into data_source (source_name, data_type) values ('CircleCI', 'CI/CD_metrics');
insert into data_source (source_name, data_type) values ('Travis CI', 'CI/CD_metrics');