use Husky_Hacks;
INSERT INTO departments (name) VALUES
('Engineering'),
('Marketing'),
('Finance'),
('Human Resources'),
('Information Technology'),
('Sales'),
('Customer Support'),
('Legal'),
('Operations'),
('Product Development'),
('Quality Assurance'),
('Supply Chain'),
('Procurement'),
('Public Relations'),
('Data Analytics'),
('Cybersecurity'),
('Business Development'),
('Corporate Strategy'),
('Risk Management'),
('Compliance'),
('Investor Relations'),
('Facilities Management'),
('Training and Development'),
('Event Planning'),
('Content Management'),
('Social Media Marketing'),
('Graphic Design'),
('Research and Development'),
('Environmental Sustainability'),
('Manufacturing'),
('Retail Operations'),
('Technical Writing'),
('Customer Success'),
('DevOps'),
('Field Services'),
('Technical Support'),
('Digital Transformation'),
('Software Implementation'),
('Hardware Engineering'),
('Cloud Infrastructure');
