insert into roles (role_id, role_title) values (1, 'Web Designer II');
insert into roles (role_id, role_title) values (2, 'General Manager');
insert into roles (role_id, role_title) values (3, 'General Manager');
insert into roles (role_id, role_title) values (4, 'Actuary');
insert into roles (role_id, role_title) values (5, 'Speech Pathologist');
insert into roles (role_id, role_title) values (6, 'Senior Developer');
insert into roles (role_id, role_title) values (7, 'Structural Engineer');
insert into roles (role_id, role_title) values (8, 'Media Manager I');
insert into roles (role_id, role_title) values (9, 'Research Nurse');
insert into roles (role_id, role_title) values (10, 'Programmer II');
insert into roles (role_id, role_title) values (11, 'Pharmacist');
insert into roles (role_id, role_title) values (12, 'Help Desk Technician');
insert into roles (role_id, role_title) values (13, 'Account Coordinator');
insert into roles (role_id, role_title) values (14, 'Sales Representative');
insert into roles (role_id, role_title) values (15, 'Social Worker');
insert into roles (role_id, role_title) values (16, 'Operator');
insert into roles (role_id, role_title) values (17, 'Research Nurse');
insert into roles (role_id, role_title) values (18, 'Project Manager');
insert into roles (role_id, role_title) values (19, 'Executive Secretary');
insert into roles (role_id, role_title) values (20, 'Sales Associate');
insert into roles (role_id, role_title) values (21, 'Business Systems Development Analyst');
insert into roles (role_id, role_title) values (22, 'Internal Auditor');
insert into roles (role_id, role_title) values (23, 'Help Desk Technician');
insert into roles (role_id, role_title) values (24, 'Software Consultant');
insert into roles (role_id, role_title) values (25, 'Software Consultant');
insert into roles (role_id, role_title) values (26, 'Structural Engineer');
insert into roles (role_id, role_title) values (27, 'Programmer Analyst II');
insert into roles (role_id, role_title) values (28, 'Cost Accountant');
insert into roles (role_id, role_title) values (29, 'Safety Technician III');
insert into roles (role_id, role_title) values (30, 'Programmer II');
insert into roles (role_id, role_title) values (31, 'Cost Accountant');
insert into roles (role_id, role_title) values (32, 'Nurse');
insert into roles (role_id, role_title) values (33, 'Graphic Designer');
insert into roles (role_id, role_title) values (34, 'Nuclear Power Engineer');
insert into roles (role_id, role_title) values (35, 'Senior Developer');
insert into roles (role_id, role_title) values (36, 'Director of Sales');
insert into roles (role_id, role_title) values (37, 'Sales Representative');
insert into roles (role_id, role_title) values (38, 'Media Manager III');
insert into roles (role_id, role_title) values (39, 'Senior Sales Associate');
insert into roles (role_id, role_title) values (40, 'Programmer Analyst III');
