use Husky_Hacks;
INSERT INTO teams (team_name, department) VALUES
('Software Development Team', 1),
('Network Engineering Team', 1),
('Digital Marketing Team', 2),
('SEO Optimization Team', 2),
('Accounting Team', 3),
('Payroll Processing Team', 3),
('Employee Relations Team', 4),
('Recruitment Team', 4),
('Infrastructure Support Team', 5),
('IT Security Team', 5),
('B2B Sales Team', 6),
('Consumer Sales Team', 6),
('Help Desk Team', 7),
('Customer Onboarding Team', 7),
('Contract Management Team', 8),
('Legal Compliance Team', 8),
('Logistics Team', 9),
('Warehouse Operations Team', 9),
('Product Design Team', 10),
('Innovation Lab Team', 10),
('QA Automation Team', 11),
('Manual Testing Team', 11),
('Shipping Team', 12),
('Supplier Relations Team', 12),
('Media Relations Team', 14),
('Content Strategy Team', 15),
('Threat Intelligence Team', 16),
('Startup Partnerships Team', 17),
('Mergers and Acquisitions Team', 18),
('Crisis Management Team', 19),
('Regulatory Affairs Team', 20),
('Shareholder Communications Team', 21),
('Office Administration Team', 22),
('Employee Training Team', 23),
('Conference Planning Team', 24),
('Creative Writing Team', 25),
('Video Production Team', 26),
('Sustainability Initiatives Team', 28),
('Retail Display Design Team', 29),
('User Documentation Team', 40);
